version: "3"
services:
        db:
                build: ./mysql/
                container_name: flask_stock50_db
                ports:
                        - "3306:3306"
                volumes:
                        - ./mysql/initdb:/docker-entrypoint-initdb.d
                        - mysql_data:/var/lib/mysql
                image: mysql_db
                environment:
                - MYSQL_ROOT_PASSWORD=12345678
        web:
                build: ./stock50_web/
                container_name: flask_stock50_web
                restart: always
                expose:
                - 5000
                depends_on:
                        - db
                        - myredis
                volumes:
                        - ./stock50_web:/app
                image: flask_web
                environment:
                - TZ=Asia/Taipei
        myredis:
                image: redis:6.0.5-alpine
        nginx:
                build: ./nginx/
                volumes:
                - "./nginx-logs:/var/log/nginx"
                container_name: template_nginx
                # restart: always
                ports:
                - "80:80"       
                depends_on:
                - web         
                extra_hosts:
                - "host.docker.internal:host-gateway" 
volumes:
    mysql_data: